name: bipyt-sp
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=2.0.0
  - pandas=2.2.2
  - python=3.10
  - pytest=8.2.2
  - sqlalchemy=2.0.31
  - psycopg2=2.9.9
  - pylint=3.2.5
  - pydantic=1.10.2
  - greenlet=2.0.1
  - dnspython=2.2.1
  - python-dotenv=0.21.0
  - six=1.16.0
  - httpx=0.27.0
  - fastapi=0.111.0
  - pyyaml=6.0
  - uvicorn=0.30.1
  - jinja2=3.1.4
  - websockets=12.0
  - markdown=3.6
  - weasyprint=62.3
  - plotly=5.22.0
