version: '3.8'
services:
  db:
    container_name: ds-review-db
    image: postgres:13.4
    restart: on-failure
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=devdb
    ports:
      - "5432:5432"
    networks:
      - internal
  backend:
    container_name: ds-review-backend
    build:
      context: .
      dockerfile: app/app.dockerfile
    environment:
      - POSTGRES_SERVER=db
    depends_on:
      - db
    restart: on-failure
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    networks:
      - internal
networks:
  internal:

