services:
  - docker:dind

image: node:18.15.0

stages:
  - dependencies
  - test
  - build
  - publish
  - doc
  - analysis

install_dependencies:
  stage: dependencies
  script:
    - npm install
  only:
    - master
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules

build_image:
  stage: build
  script:
    - npm link @angular/cli@15.0.0
    - npm run build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull

compodoc:
  stage: doc
  script:
    - npm install -g @compodoc/compodoc
    - compodoc -p tsconfig.json
  only:
    - master
  artifacts:
    paths:
      - $CI_PROJECT_DIR/documentation

eslint_analysis:
  stage: analysis
  script:
    - npm install -g @angular/cli
    - npm install
    - npm install -g eslint-html-reporter
    - ./node_modules/.bin/eslint "src/**/*.ts" -f html -o eslint-report.html || true
  artifacts:
    paths:
      - eslint-report.html
    expire_in: 1 week