name: vylet-ner
channels:
  - conda-forge
dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - gensim
  - nltk
  - numpy
  - pandas
  - ca-certificates
  - certifi
  - openssl
  - jupyterlab
  - notebook
  - pydantic
  - fastapi
  - streamlit
  - transformers
