version: '3'
services:
    nginx:
        image: nginx:1.20
        restart: always
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        networks:
            - internal
    php:
        build: docker/php8.1 # or docker/php7.4, do not forget to change paths in "volumes" then
        restart: always
        volumes:
            - ./:/var/www/html
            - ./docker/php8.1/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./docker/php8.1/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        ports:
            - "9000:9000"
        networks:
            - internal
    postgres:
        build: docker/postgres
        restart: always
        environment:
            - POSTGRES_DB=devdb
            - POSTGRES_USER=dev
            - POSTGRES_PASSWORD=pass
        ports:
            - "5432:5432"
        # volumes:
        #     - ./docker/postgres/data:/var/lib/postgresql/data
        networks:
            - internal

networks:
    internal:
